version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    network_mode: "host"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network_mode: "host"