version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    cap_add:
      - NET_ADMIN  # Add necessary capabilities for network scanning

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge